services:
  nginx:
    build:
      context: ../../
      dockerfile: ./docker/dev/Dockerfile.nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      frontend:
        condition: service_started
      backend:
        condition: service_started
      postgres:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - app-network
    mem_limit: 256m
    cpus: 0.25

  frontend:
    build:
      context: ../../
      dockerfile: ./docker/dev/Dockerfile.frontend
    container_name: frontend
    env_file:
      - ../../env/development.env
    volumes:
      - ../../frontend:/frontend
      - frontend-node-modules:/frontend/node_modules
    expose:
      - "5173"
    networks:
      - app-network
    mem_limit: 1g
    cpus: 0.5

  backend:
    build:
      context: ../../
      dockerfile: ./docker/dev/Dockerfile.backend
    container_name: backend
    env_file:
      - ../../env/development.env
    volumes:
      - ../../backend:/backend
      - backend-node-modules:/backend/node_modules
    expose:
      - "5000"
    networks:
      - app-network
    mem_limit: 1g
    cpus: 0.75

  postgres:
    image: postgres:17.9-alpine3.23
    container_name: postgresql
    env_file:
      - ../../env/development.env
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - app-network
    mem_limit: 1g
    cpus: 1

  redis:
    image: redis:8.2-alpine
    container_name: redis
    restart: unless-stopped
    expose:
      - "6379"
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - redis-data:/data
    mem_limit: 256m
    cpus: 0.25
    command: ["redis-server", "--save", "60", "1", "--appendonly", "yes"]

volumes:
  postgres-data:
  frontend-node-modules:
  backend-node-modules:
  redis-data:

networks:
  app-network:
    driver: bridge
